name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  SKIP_DEPLOYMENT: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build project
        run: npm run build
      - name: Run tests
        run: CI=true npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT != 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT != 'true' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify_success:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: success()
    steps:
      - name: Send success notification to Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: "Deployment succeeded!"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: "Deployment has been successfully completed!"

  notify_failure:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: failure()
    steps:
      - name: Send failure notification to Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: |
            **Deployment failed!**
            **Commit that caused the failure**: ${{ github.event.head_commit.message }}
            Check the logs for details.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: "Deployment failed!"
